### ISSUE TITLE
replace_mesh not setting shapeType attribute on marker

### ISSUE THREAD

**Issue by domrab** [mottosso/ragdoll#6]
I feel like calling `replace_mesh()` should automatically set the `shapeType` attribute to `Mesh`.

This is not a problem with markers that get created on geometry as they get their shape type set to `Mesh` by default as far as I can tell but replacing the mesh on markers that were created for joints seemingly does nothing.

After running the code in the bottom, visually nothing will happen in scene. The marker will still display as sphere. Only after setting `shapeType` to `Mesh` we will see the effect.

(Or is this intended?)

```
from ragdoll import api as ragApi

jnt = cmds.joint()
torus = cmds.polyTorus(ch=False)[0]

solver = ragApi.create_solver('test_rSolver')
marker = ragApi.assign_marker(jnt, solver)

enum_attr = cmds.attributeQuery('shapeType', n=marker, listEnum=True)
print(f"Shapetype {enum_attr}: {cmds.getAttr(marker + '.shapeType')}")

ragApi.replace_mesh(marker, cmds.listRelatives(torus)[0])

print(f"Shapetype {enum_attr}: {cmds.getAttr(marker + '.shapeType')}")
print("Should switch to 4 -> Mesh")
```

**Comment by mottosso** [comment]
Hey @domrab. True, I can't recall why this is currently only happening when calling `Replace Mesh` from the UI.

- https://github.com/mottosso/ragdoll/blob/b959b76b2984c405c60be22ea24549e6b0d9cea4/ragdoll/interactive.py#L3144

It would make sense to set this attribute from the API call instead, I'll change this now and it'll show up in the next release. Thanks for the suggestion!
