### ISSUE TITLE
ragdoll.commands.assign_marker unused group argument

### ISSUE THREAD

**Issue by domrab** [mottosso/ragdoll#8]
The group argument in `ragdoll.commands.assign_marker()` is unused.
```
from ragdoll import commands as ragCmds

cube = ragCmds.cmdx.encode(cmds.polyCube(ch=False)[0])
solver = ragCmds.create_solver("test")
group = ragCmds.create_group(solver, "group")
marker = ragCmds.assign_marker(cube, solver, group=group)

# marker is not connected to group
for con in group.connections(source=True, destination=False):
    print(con)
```

**Comment by mottosso** [comment]
Where did you find this group argument? The group may be passed as the second argument, in place of the `solver`.

```py
ragCmds.assign_marker(cube, group)
```

https://github.com/mottosso/ragdoll/blob/b959b76b2984c405c60be22ea24549e6b0d9cea4/ragdoll/commands.py#L82

Also keep in mind that `ragdoll.api` is the official API and that the `commands` module is internal and may change over time.

**Comment by domrab** [comment]
Hah! Finally figure out how to copy lines!

https://github.com/mottosso/ragdoll/blob/b959b76b2984c405c60be22ea24549e6b0d9cea4/ragdoll/commands.py#L278

I started using `ragdoll.api` but ran into some issues (which to be fair were mostly related me not knowing what I was doing lol).
I was unaware that the group may be passed in instead of the solver and `cmdx` is really convenient :D
Well, you live and learn. Thanks! Time to go back to `ragdoll.api`
